import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { Bell, ShieldAlert, Award } from 'lucide-react';
import MatchScoreCard from '../components/MatchScoreCard';

const MatchResults = () => {
  const [matches, setMatches] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filterStatus, setFilterStatus] = useState('pending'); // Default to showing active alarms

  const fetchMatches = async () => {
    try {
      setLoading(true);
      const response = await axios.get(`/api/matches?status=${filterStatus}`);
      if (response.data.success) {
        setMatches(response.data.data);
      }
    } catch (err) {
      console.error('Failed to load matching suspect logs:', err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchMatches();
  }, [filterStatus]);

  const handleStatusUpdate = (matchId, newStatus) => {
    // If the filter status is set to something specific, filter out the updated card immediately
    // to match standard inbox pattern, or show its verified state if searching all
    if (filterStatus) {
      setMatches(prev => prev.filter(m => m._id !== matchId));
    } else {
      setMatches(prev => prev.map(m => m._id === matchId ? { ...m, status: newStatus } : m));
    }
  };

  return (
    <div>
      {/* Page Header */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '2.0rem',
        flexWrap: 'wrap',
        gap: '1rem'
      }}>
        <div>
          <h2 style={{ fontSize: '1.25rem', color: '#ffffff', fontFamily: 'Outfit' }}>Automated Suspect Match Alerts</h2>
          <p style={{ color: '#94a3b8', fontSize: '0.85rem' }}>Verify or dismiss suspect overlapping reports generated by the matching algorithm</p>
        </div>

        {/* Filter statuses tabs */}
        <div className="glass-panel" style={{ padding: '0.25rem', display: 'flex', gap: '0.25rem', borderRadius: '10px' }}>
          <button
            onClick={() => setFilterStatus('pending')}
            className="btn"
            style={{
              padding: '0.4rem 0.9rem',
              fontSize: '0.75rem',
              borderRadius: '8px',
              background: filterStatus === 'pending' ? 'rgba(59, 130, 246, 0.15)' : 'transparent',
              color: filterStatus === 'pending' ? '#3b82f6' : '#94a3b8',
              boxShadow: 'none'
            }}
          >
            Active Alarms
          </button>
          <button
            onClick={() => setFilterStatus('verified')}
            className="btn"
            style={{
              padding: '0.4rem 0.9rem',
              fontSize: '0.75rem',
              borderRadius: '8px',
              background: filterStatus === 'verified' ? 'rgba(16, 185, 129, 0.15)' : 'transparent',
              color: filterStatus === 'verified' ? '#10b981' : '#94a3b8',
              boxShadow: 'none'
            }}
          >
            Verified Connections
          </button>
          <button
            onClick={() => setFilterStatus('dismissed')}
            className="btn"
            style={{
              padding: '0.4rem 0.9rem',
              fontSize: '0.75rem',
              borderRadius: '8px',
              background: filterStatus === 'dismissed' ? 'rgba(255, 255, 255, 0.05)' : 'transparent',
              color: filterStatus === 'dismissed' ? '#f8fafc' : '#94a3b8',
              boxShadow: 'none'
            }}
          >
            Dismissed Alerts
          </button>
        </div>
      </div>

      {/* Matches Alarms List */}
      {loading ? (
        <div style={{ textAlign: 'center', padding: '3rem', color: '#94a3b8' }}>
          <p>Querying matching engines...</p>
        </div>
      ) : matches.length === 0 ? (
        <div className="glass-panel" style={{ padding: '4rem', textAlign: 'center', color: '#64748b' }}>
          <Bell size={40} style={{ marginBottom: '1rem' }} />
          <h3>No Match Results</h3>
          <p style={{ fontSize: '0.85rem', marginTop: '0.25rem' }}>
            {filterStatus === 'pending' 
              ? 'No active alarms exist. Your caseload is completely matched and vetted.' 
              : `No alerts match status filter '${filterStatus}'.`}
          </p>
        </div>
      ) : (
        <div style={{ maxWidth: '800px' }}>
          {matches.map(match => (
            <MatchScoreCard 
              key={match._id} 
              match={match} 
              onStatusUpdate={handleStatusUpdate} 
            />
          ))}
        </div>
      )}
    </div>
  );
};

export default MatchResults;
